---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by weihao.lv.
--- DateTime: 2021/5/26 2:56 下午
--- 可重入解锁

-- 加锁
-- 加锁键
local lockKey = KEYS[1]
-- 代表重入请求的唯一 id
local requestId = ARGV[1]

-- key 不存在说明已经过期或者被释放了，直接 return 1 标示解锁成功
if redis.call('EXISTS', lockKey) == 0 then
    return 1
end

-- 获取当前锁
local lockTable = redis.call("HMGET", lockKey, 'requestId', 'count')
if (requestId ~= lockTable[1]) then
    -- 请求唯一 id 不同说明不是同一次业务请求，无法解锁
    return 0
elseif (tonumber(lockTable[2]) <= 1) then
    -- 最后一次解锁，直接删除锁
    redis.call('DEL', lockKey)
    return 1
else
    -- 解锁一次
    redis.call("HINCRBY", lockKey, 'count', -1)
    return 1
end
